export interface CountryCodeEntry {
  name: string;
  flag: string;
  code: string;
  isoCode: string;
  minLength: number;
  maxLength: number;
}

export const COUNTRY_CODES: CountryCodeEntry[] = [
  { name: 'Afghanistan', flag: '\u{1F1E6}\u{1F1EB}', code: '+93', isoCode: 'AF', minLength: 9, maxLength: 9 },
  { name: 'Albania', flag: '\u{1F1E6}\u{1F1F1}', code: '+355', isoCode: 'AL', minLength: 9, maxLength: 9 },
  { name: 'Algeria', flag: '\u{1F1E9}\u{1F1FF}', code: '+213', isoCode: 'DZ', minLength: 9, maxLength: 9 },
  { name: 'Andorra', flag: '\u{1F1E6}\u{1F1E9}', code: '+376', isoCode: 'AD', minLength: 6, maxLength: 9 },
  { name: 'Angola', flag: '\u{1F1E6}\u{1F1F4}', code: '+244', isoCode: 'AO', minLength: 9, maxLength: 9 },
  { name: 'Argentina', flag: '\u{1F1E6}\u{1F1F7}', code: '+54', isoCode: 'AR', minLength: 10, maxLength: 11 },
  { name: 'Armenia', flag: '\u{1F1E6}\u{1F1F2}', code: '+374', isoCode: 'AM', minLength: 8, maxLength: 8 },
  { name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}', code: '+61', isoCode: 'AU', minLength: 9, maxLength: 9 },
  { name: 'Austria', flag: '\u{1F1E6}\u{1F1F9}', code: '+43', isoCode: 'AT', minLength: 10, maxLength: 13 },
  { name: 'Azerbaijan', flag: '\u{1F1E6}\u{1F1FF}', code: '+994', isoCode: 'AZ', minLength: 9, maxLength: 9 },
  { name: 'Bahrain', flag: '\u{1F1E7}\u{1F1ED}', code: '+973', isoCode: 'BH', minLength: 8, maxLength: 8 },
  { name: 'Bangladesh', flag: '\u{1F1E7}\u{1F1E9}', code: '+880', isoCode: 'BD', minLength: 10, maxLength: 10 },
  { name: 'Belarus', flag: '\u{1F1E7}\u{1F1FE}', code: '+375', isoCode: 'BY', minLength: 9, maxLength: 10 },
  { name: 'Belgium', flag: '\u{1F1E7}\u{1F1EA}', code: '+32', isoCode: 'BE', minLength: 9, maxLength: 9 },
  { name: 'Belize', flag: '\u{1F1E7}\u{1F1FF}', code: '+501', isoCode: 'BZ', minLength: 7, maxLength: 7 },
  { name: 'Benin', flag: '\u{1F1E7}\u{1F1EF}', code: '+229', isoCode: 'BJ', minLength: 8, maxLength: 8 },
  { name: 'Bhutan', flag: '\u{1F1E7}\u{1F1F9}', code: '+975', isoCode: 'BT', minLength: 8, maxLength: 8 },
  { name: 'Bolivia', flag: '\u{1F1E7}\u{1F1F4}', code: '+591', isoCode: 'BO', minLength: 8, maxLength: 8 },
  { name: 'Bosnia and Herzegovina', flag: '\u{1F1E7}\u{1F1E6}', code: '+387', isoCode: 'BA', minLength: 8, maxLength: 8 },
  { name: 'Botswana', flag: '\u{1F1E7}\u{1F1FC}', code: '+267', isoCode: 'BW', minLength: 7, maxLength: 8 },
  { name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}', code: '+55', isoCode: 'BR', minLength: 10, maxLength: 11 },
  { name: 'Brunei', flag: '\u{1F1E7}\u{1F1F3}', code: '+673', isoCode: 'BN', minLength: 7, maxLength: 7 },
  { name: 'Bulgaria', flag: '\u{1F1E7}\u{1F1EC}', code: '+359', isoCode: 'BG', minLength: 9, maxLength: 9 },
  { name: 'Burkina Faso', flag: '\u{1F1E7}\u{1F1EB}', code: '+226', isoCode: 'BF', minLength: 8, maxLength: 8 },
  { name: 'Burundi', flag: '\u{1F1E7}\u{1F1EE}', code: '+257', isoCode: 'BI', minLength: 8, maxLength: 8 },
  { name: 'Cambodia', flag: '\u{1F1F0}\u{1F1ED}', code: '+855', isoCode: 'KH', minLength: 8, maxLength: 9 },
  { name: 'Cameroon', flag: '\u{1F1E8}\u{1F1F2}', code: '+237', isoCode: 'CM', minLength: 9, maxLength: 9 },
  { name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}', code: '+1', isoCode: 'CA', minLength: 10, maxLength: 10 },
  { name: 'Chad', flag: '\u{1F1F9}\u{1F1E9}', code: '+235', isoCode: 'TD', minLength: 8, maxLength: 8 },
  { name: 'Chile', flag: '\u{1F1E8}\u{1F1F1}', code: '+56', isoCode: 'CL', minLength: 9, maxLength: 9 },
  { name: 'China', flag: '\u{1F1E8}\u{1F1F3}', code: '+86', isoCode: 'CN', minLength: 11, maxLength: 11 },
  { name: 'Colombia', flag: '\u{1F1E8}\u{1F1F4}', code: '+57', isoCode: 'CO', minLength: 10, maxLength: 10 },
  { name: 'Congo', flag: '\u{1F1E8}\u{1F1EC}', code: '+242', isoCode: 'CG', minLength: 9, maxLength: 9 },
  { name: 'Costa Rica', flag: '\u{1F1E8}\u{1F1F7}', code: '+506', isoCode: 'CR', minLength: 8, maxLength: 8 },
  { name: 'Croatia', flag: '\u{1F1ED}\u{1F1F7}', code: '+385', isoCode: 'HR', minLength: 8, maxLength: 9 },
  { name: 'Cuba', flag: '\u{1F1E8}\u{1F1FA}', code: '+53', isoCode: 'CU', minLength: 8, maxLength: 8 },
  { name: 'Cyprus', flag: '\u{1F1E8}\u{1F1FE}', code: '+357', isoCode: 'CY', minLength: 8, maxLength: 8 },
  { name: 'Czech Republic', flag: '\u{1F1E8}\u{1F1FF}', code: '+420', isoCode: 'CZ', minLength: 9, maxLength: 9 },
  { name: 'Denmark', flag: '\u{1F1E9}\u{1F1F0}', code: '+45', isoCode: 'DK', minLength: 8, maxLength: 8 },
  { name: 'Djibouti', flag: '\u{1F1E9}\u{1F1EF}', code: '+253', isoCode: 'DJ', minLength: 8, maxLength: 8 },
  { name: 'Dominican Republic', flag: '\u{1F1E9}\u{1F1F4}', code: '+1', isoCode: 'DO', minLength: 10, maxLength: 10 },
  { name: 'DR Congo', flag: '\u{1F1E8}\u{1F1E9}', code: '+243', isoCode: 'CD', minLength: 9, maxLength: 9 },
  { name: 'Ecuador', flag: '\u{1F1EA}\u{1F1E8}', code: '+593', isoCode: 'EC', minLength: 9, maxLength: 9 },
  { name: 'Egypt', flag: '\u{1F1EA}\u{1F1EC}', code: '+20', isoCode: 'EG', minLength: 10, maxLength: 10 },
  { name: 'El Salvador', flag: '\u{1F1F8}\u{1F1FB}', code: '+503', isoCode: 'SV', minLength: 8, maxLength: 8 },
  { name: 'Eritrea', flag: '\u{1F1EA}\u{1F1F7}', code: '+291', isoCode: 'ER', minLength: 7, maxLength: 7 },
  { name: 'Estonia', flag: '\u{1F1EA}\u{1F1EA}', code: '+372', isoCode: 'EE', minLength: 7, maxLength: 8 },
  { name: 'Eswatini', flag: '\u{1F1F8}\u{1F1FF}', code: '+268', isoCode: 'SZ', minLength: 8, maxLength: 8 },
  { name: 'Ethiopia', flag: '\u{1F1EA}\u{1F1F9}', code: '+251', isoCode: 'ET', minLength: 9, maxLength: 9 },
  { name: 'Fiji', flag: '\u{1F1EB}\u{1F1EF}', code: '+679', isoCode: 'FJ', minLength: 7, maxLength: 7 },
  { name: 'Finland', flag: '\u{1F1EB}\u{1F1EE}', code: '+358', isoCode: 'FI', minLength: 9, maxLength: 11 },
  { name: 'France', flag: '\u{1F1EB}\u{1F1F7}', code: '+33', isoCode: 'FR', minLength: 9, maxLength: 9 },
  { name: 'Gabon', flag: '\u{1F1EC}\u{1F1E6}', code: '+241', isoCode: 'GA', minLength: 7, maxLength: 8 },
  { name: 'Gambia', flag: '\u{1F1EC}\u{1F1F2}', code: '+220', isoCode: 'GM', minLength: 7, maxLength: 7 },
  { name: 'Georgia', flag: '\u{1F1EC}\u{1F1EA}', code: '+995', isoCode: 'GE', minLength: 9, maxLength: 9 },
  { name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}', code: '+49', isoCode: 'DE', minLength: 10, maxLength: 12 },
  { name: 'Ghana', flag: '\u{1F1EC}\u{1F1ED}', code: '+233', isoCode: 'GH', minLength: 9, maxLength: 9 },
  { name: 'Greece', flag: '\u{1F1EC}\u{1F1F7}', code: '+30', isoCode: 'GR', minLength: 10, maxLength: 10 },
  { name: 'Guatemala', flag: '\u{1F1EC}\u{1F1F9}', code: '+502', isoCode: 'GT', minLength: 8, maxLength: 8 },
  { name: 'Guinea', flag: '\u{1F1EC}\u{1F1F3}', code: '+224', isoCode: 'GN', minLength: 9, maxLength: 9 },
  { name: 'Haiti', flag: '\u{1F1ED}\u{1F1F9}', code: '+509', isoCode: 'HT', minLength: 8, maxLength: 8 },
  { name: 'Honduras', flag: '\u{1F1ED}\u{1F1F3}', code: '+504', isoCode: 'HN', minLength: 8, maxLength: 8 },
  { name: 'Hong Kong', flag: '\u{1F1ED}\u{1F1F0}', code: '+852', isoCode: 'HK', minLength: 8, maxLength: 8 },
  { name: 'Hungary', flag: '\u{1F1ED}\u{1F1FA}', code: '+36', isoCode: 'HU', minLength: 9, maxLength: 9 },
  { name: 'Iceland', flag: '\u{1F1EE}\u{1F1F8}', code: '+354', isoCode: 'IS', minLength: 7, maxLength: 7 },
  { name: 'India', flag: '\u{1F1EE}\u{1F1F3}', code: '+91', isoCode: 'IN', minLength: 10, maxLength: 10 },
  { name: 'Indonesia', flag: '\u{1F1EE}\u{1F1E9}', code: '+62', isoCode: 'ID', minLength: 9, maxLength: 12 },
  { name: 'Iran', flag: '\u{1F1EE}\u{1F1F7}', code: '+98', isoCode: 'IR', minLength: 10, maxLength: 10 },
  { name: 'Iraq', flag: '\u{1F1EE}\u{1F1F6}', code: '+964', isoCode: 'IQ', minLength: 10, maxLength: 10 },
  { name: 'Ireland', flag: '\u{1F1EE}\u{1F1EA}', code: '+353', isoCode: 'IE', minLength: 9, maxLength: 9 },
  { name: 'Israel', flag: '\u{1F1EE}\u{1F1F1}', code: '+972', isoCode: 'IL', minLength: 9, maxLength: 9 },
  { name: 'Italy', flag: '\u{1F1EE}\u{1F1F9}', code: '+39', isoCode: 'IT', minLength: 9, maxLength: 11 },
  { name: 'Ivory Coast', flag: '\u{1F1E8}\u{1F1EE}', code: '+225', isoCode: 'CI', minLength: 8, maxLength: 8 },
  { name: 'Jamaica', flag: '\u{1F1EF}\u{1F1F2}', code: '+1', isoCode: 'JM', minLength: 10, maxLength: 10 },
  { name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}', code: '+81', isoCode: 'JP', minLength: 10, maxLength: 11 },
  { name: 'Jordan', flag: '\u{1F1EF}\u{1F1F4}', code: '+962', isoCode: 'JO', minLength: 9, maxLength: 9 },
  { name: 'Kazakhstan', flag: '\u{1F1F0}\u{1F1FF}', code: '+7', isoCode: 'KZ', minLength: 10, maxLength: 10 },
  { name: 'Kenya', flag: '\u{1F1F0}\u{1F1EA}', code: '+254', isoCode: 'KE', minLength: 9, maxLength: 9 },
  { name: 'Kuwait', flag: '\u{1F1F0}\u{1F1FC}', code: '+965', isoCode: 'KW', minLength: 8, maxLength: 8 },
  { name: 'Kyrgyzstan', flag: '\u{1F1F0}\u{1F1EC}', code: '+996', isoCode: 'KG', minLength: 9, maxLength: 9 },
  { name: 'Laos', flag: '\u{1F1F1}\u{1F1E6}', code: '+856', isoCode: 'LA', minLength: 8, maxLength: 9 },
  { name: 'Latvia', flag: '\u{1F1F1}\u{1F1FB}', code: '+371', isoCode: 'LV', minLength: 8, maxLength: 8 },
  { name: 'Lebanon', flag: '\u{1F1F1}\u{1F1E7}', code: '+961', isoCode: 'LB', minLength: 7, maxLength: 8 },
  { name: 'Lesotho', flag: '\u{1F1F1}\u{1F1F8}', code: '+266', isoCode: 'LS', minLength: 8, maxLength: 8 },
  { name: 'Liberia', flag: '\u{1F1F1}\u{1F1F7}', code: '+231', isoCode: 'LR', minLength: 7, maxLength: 8 },
  { name: 'Libya', flag: '\u{1F1F1}\u{1F1FE}', code: '+218', isoCode: 'LY', minLength: 9, maxLength: 9 },
  { name: 'Liechtenstein', flag: '\u{1F1F1}\u{1F1EE}', code: '+423', isoCode: 'LI', minLength: 7, maxLength: 9 },
  { name: 'Lithuania', flag: '\u{1F1F1}\u{1F1F9}', code: '+370', isoCode: 'LT', minLength: 8, maxLength: 8 },
  { name: 'Luxembourg', flag: '\u{1F1F1}\u{1F1FA}', code: '+352', isoCode: 'LU', minLength: 9, maxLength: 11 },
  { name: 'Madagascar', flag: '\u{1F1F2}\u{1F1EC}', code: '+261', isoCode: 'MG', minLength: 9, maxLength: 9 },
  { name: 'Malawi', flag: '\u{1F1F2}\u{1F1FC}', code: '+265', isoCode: 'MW', minLength: 9, maxLength: 9 },
  { name: 'Malaysia', flag: '\u{1F1F2}\u{1F1FE}', code: '+60', isoCode: 'MY', minLength: 9, maxLength: 10 },
  { name: 'Maldives', flag: '\u{1F1F2}\u{1F1FB}', code: '+960', isoCode: 'MV', minLength: 7, maxLength: 7 },
  { name: 'Mali', flag: '\u{1F1F2}\u{1F1F1}', code: '+223', isoCode: 'ML', minLength: 8, maxLength: 8 },
  { name: 'Malta', flag: '\u{1F1F2}\u{1F1F9}', code: '+356', isoCode: 'MT', minLength: 8, maxLength: 8 },
  { name: 'Mauritania', flag: '\u{1F1F2}\u{1F1F7}', code: '+222', isoCode: 'MR', minLength: 8, maxLength: 8 },
  { name: 'Mauritius', flag: '\u{1F1F2}\u{1F1FA}', code: '+230', isoCode: 'MU', minLength: 8, maxLength: 8 },
  { name: 'Mexico', flag: '\u{1F1F2}\u{1F1FD}', code: '+52', isoCode: 'MX', minLength: 10, maxLength: 10 },
  { name: 'Moldova', flag: '\u{1F1F2}\u{1F1E9}', code: '+373', isoCode: 'MD', minLength: 8, maxLength: 8 },
  { name: 'Monaco', flag: '\u{1F1F2}\u{1F1E8}', code: '+377', isoCode: 'MC', minLength: 8, maxLength: 9 },
  { name: 'Mongolia', flag: '\u{1F1F2}\u{1F1F3}', code: '+976', isoCode: 'MN', minLength: 8, maxLength: 8 },
  { name: 'Montenegro', flag: '\u{1F1F2}\u{1F1EA}', code: '+382', isoCode: 'ME', minLength: 8, maxLength: 8 },
  { name: 'Morocco', flag: '\u{1F1F2}\u{1F1E6}', code: '+212', isoCode: 'MA', minLength: 9, maxLength: 9 },
  { name: 'Mozambique', flag: '\u{1F1F2}\u{1F1FF}', code: '+258', isoCode: 'MZ', minLength: 9, maxLength: 9 },
  { name: 'Myanmar', flag: '\u{1F1F2}\u{1F1F2}', code: '+95', isoCode: 'MM', minLength: 8, maxLength: 10 },
  { name: 'Namibia', flag: '\u{1F1F3}\u{1F1E6}', code: '+264', isoCode: 'NA', minLength: 9, maxLength: 9 },
  { name: 'Nepal', flag: '\u{1F1F3}\u{1F1F5}', code: '+977', isoCode: 'NP', minLength: 10, maxLength: 10 },
  { name: 'Netherlands', flag: '\u{1F1F3}\u{1F1F1}', code: '+31', isoCode: 'NL', minLength: 9, maxLength: 9 },
  { name: 'New Zealand', flag: '\u{1F1F3}\u{1F1FF}', code: '+64', isoCode: 'NZ', minLength: 8, maxLength: 10 },
  { name: 'Nicaragua', flag: '\u{1F1F3}\u{1F1EE}', code: '+505', isoCode: 'NI', minLength: 8, maxLength: 8 },
  { name: 'Niger', flag: '\u{1F1F3}\u{1F1EA}', code: '+227', isoCode: 'NE', minLength: 8, maxLength: 8 },
  { name: 'Nigeria', flag: '\u{1F1F3}\u{1F1EC}', code: '+234', isoCode: 'NG', minLength: 10, maxLength: 10 },
  { name: 'North Korea', flag: '\u{1F1F0}\u{1F1F5}', code: '+850', isoCode: 'KP', minLength: 9, maxLength: 10 },
  { name: 'North Macedonia', flag: '\u{1F1F2}\u{1F1F0}', code: '+389', isoCode: 'MK', minLength: 8, maxLength: 8 },
  { name: 'Norway', flag: '\u{1F1F3}\u{1F1F4}', code: '+47', isoCode: 'NO', minLength: 8, maxLength: 8 },
  { name: 'Oman', flag: '\u{1F1F4}\u{1F1F2}', code: '+968', isoCode: 'OM', minLength: 8, maxLength: 8 },
  { name: 'Pakistan', flag: '\u{1F1F5}\u{1F1F0}', code: '+92', isoCode: 'PK', minLength: 10, maxLength: 10 },
  { name: 'Palestine', flag: '\u{1F1F5}\u{1F1F8}', code: '+970', isoCode: 'PS', minLength: 9, maxLength: 9 },
  { name: 'Panama', flag: '\u{1F1F5}\u{1F1E6}', code: '+507', isoCode: 'PA', minLength: 8, maxLength: 8 },
  { name: 'Papua New Guinea', flag: '\u{1F1F5}\u{1F1EC}', code: '+675', isoCode: 'PG', minLength: 8, maxLength: 8 },
  { name: 'Paraguay', flag: '\u{1F1F5}\u{1F1FE}', code: '+595', isoCode: 'PY', minLength: 9, maxLength: 9 },
  { name: 'Peru', flag: '\u{1F1F5}\u{1F1EA}', code: '+51', isoCode: 'PE', minLength: 9, maxLength: 9 },
  { name: 'Philippines', flag: '\u{1F1F5}\u{1F1ED}', code: '+63', isoCode: 'PH', minLength: 10, maxLength: 10 },
  { name: 'Poland', flag: '\u{1F1F5}\u{1F1F1}', code: '+48', isoCode: 'PL', minLength: 9, maxLength: 9 },
  { name: 'Portugal', flag: '\u{1F1F5}\u{1F1F9}', code: '+351', isoCode: 'PT', minLength: 9, maxLength: 9 },
  { name: 'Qatar', flag: '\u{1F1F6}\u{1F1E6}', code: '+974', isoCode: 'QA', minLength: 8, maxLength: 8 },
  { name: 'Romania', flag: '\u{1F1F7}\u{1F1F4}', code: '+40', isoCode: 'RO', minLength: 9, maxLength: 9 },
  { name: 'Russia', flag: '\u{1F1F7}\u{1F1FA}', code: '+7', isoCode: 'RU', minLength: 10, maxLength: 10 },
  { name: 'Rwanda', flag: '\u{1F1F7}\u{1F1FC}', code: '+250', isoCode: 'RW', minLength: 9, maxLength: 9 },
  { name: 'Saudi Arabia', flag: '\u{1F1F8}\u{1F1E6}', code: '+966', isoCode: 'SA', minLength: 9, maxLength: 9 },
  { name: 'Senegal', flag: '\u{1F1F8}\u{1F1F3}', code: '+221', isoCode: 'SN', minLength: 9, maxLength: 9 },
  { name: 'Serbia', flag: '\u{1F1F7}\u{1F1F8}', code: '+381', isoCode: 'RS', minLength: 9, maxLength: 9 },
  { name: 'Sierra Leone', flag: '\u{1F1F8}\u{1F1F1}', code: '+232', isoCode: 'SL', minLength: 8, maxLength: 8 },
  { name: 'Singapore', flag: '\u{1F1F8}\u{1F1EC}', code: '+65', isoCode: 'SG', minLength: 8, maxLength: 8 },
  { name: 'Slovakia', flag: '\u{1F1F8}\u{1F1F0}', code: '+421', isoCode: 'SK', minLength: 9, maxLength: 9 },
  { name: 'Slovenia', flag: '\u{1F1F8}\u{1F1EE}', code: '+386', isoCode: 'SI', minLength: 8, maxLength: 8 },
  { name: 'Somalia', flag: '\u{1F1F8}\u{1F1F4}', code: '+252', isoCode: 'SO', minLength: 8, maxLength: 9 },
  { name: 'South Africa', flag: '\u{1F1FF}\u{1F1E6}', code: '+27', isoCode: 'ZA', minLength: 9, maxLength: 9 },
  { name: 'South Korea', flag: '\u{1F1F0}\u{1F1F7}', code: '+82', isoCode: 'KR', minLength: 9, maxLength: 10 },
  { name: 'South Sudan', flag: '\u{1F1F8}\u{1F1F8}', code: '+211', isoCode: 'SS', minLength: 9, maxLength: 9 },
  { name: 'Spain', flag: '\u{1F1EA}\u{1F1F8}', code: '+34', isoCode: 'ES', minLength: 9, maxLength: 9 },
  { name: 'Sri Lanka', flag: '\u{1F1F1}\u{1F1F0}', code: '+94', isoCode: 'LK', minLength: 9, maxLength: 9 },
  { name: 'Sudan', flag: '\u{1F1F8}\u{1F1E9}', code: '+249', isoCode: 'SD', minLength: 9, maxLength: 9 },
  { name: 'Sweden', flag: '\u{1F1F8}\u{1F1EA}', code: '+46', isoCode: 'SE', minLength: 9, maxLength: 9 },
  { name: 'Switzerland', flag: '\u{1F1E8}\u{1F1ED}', code: '+41', isoCode: 'CH', minLength: 9, maxLength: 9 },
  { name: 'Syria', flag: '\u{1F1F8}\u{1F1FE}', code: '+963', isoCode: 'SY', minLength: 9, maxLength: 9 },
  { name: 'Taiwan', flag: '\u{1F1F9}\u{1F1FC}', code: '+886', isoCode: 'TW', minLength: 9, maxLength: 9 },
  { name: 'Tajikistan', flag: '\u{1F1F9}\u{1F1EF}', code: '+992', isoCode: 'TJ', minLength: 9, maxLength: 9 },
  { name: 'Tanzania', flag: '\u{1F1F9}\u{1F1FF}', code: '+255', isoCode: 'TZ', minLength: 9, maxLength: 9 },
  { name: 'Thailand', flag: '\u{1F1F9}\u{1F1ED}', code: '+66', isoCode: 'TH', minLength: 9, maxLength: 9 },
  { name: 'Togo', flag: '\u{1F1F9}\u{1F1EC}', code: '+228', isoCode: 'TG', minLength: 8, maxLength: 8 },
  { name: 'Trinidad and Tobago', flag: '\u{1F1F9}\u{1F1F9}', code: '+1', isoCode: 'TT', minLength: 10, maxLength: 10 },
  { name: 'Tunisia', flag: '\u{1F1F9}\u{1F1F3}', code: '+216', isoCode: 'TN', minLength: 8, maxLength: 8 },
  { name: 'Turkey', flag: '\u{1F1F9}\u{1F1F7}', code: '+90', isoCode: 'TR', minLength: 10, maxLength: 10 },
  { name: 'Turkmenistan', flag: '\u{1F1F9}\u{1F1F2}', code: '+993', isoCode: 'TM', minLength: 8, maxLength: 8 },
  { name: 'Uganda', flag: '\u{1F1FA}\u{1F1EC}', code: '+256', isoCode: 'UG', minLength: 9, maxLength: 9 },
  { name: 'Ukraine', flag: '\u{1F1FA}\u{1F1E6}', code: '+380', isoCode: 'UA', minLength: 9, maxLength: 9 },
  { name: 'United Arab Emirates', flag: '\u{1F1E6}\u{1F1EA}', code: '+971', isoCode: 'AE', minLength: 9, maxLength: 9 },
  { name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}', code: '+44', isoCode: 'GB', minLength: 10, maxLength: 10 },
  { name: 'United States', flag: '\u{1F1FA}\u{1F1F8}', code: '+1', isoCode: 'US', minLength: 10, maxLength: 10 },
  { name: 'Uruguay', flag: '\u{1F1FA}\u{1F1FE}', code: '+598', isoCode: 'UY', minLength: 8, maxLength: 8 },
  { name: 'Uzbekistan', flag: '\u{1F1FA}\u{1F1FF}', code: '+998', isoCode: 'UZ', minLength: 9, maxLength: 9 },
  { name: 'Venezuela', flag: '\u{1F1FB}\u{1F1EA}', code: '+58', isoCode: 'VE', minLength: 10, maxLength: 10 },
  { name: 'Vietnam', flag: '\u{1F1FB}\u{1F1F3}', code: '+84', isoCode: 'VN', minLength: 9, maxLength: 10 },
  { name: 'Yemen', flag: '\u{1F1FE}\u{1F1EA}', code: '+967', isoCode: 'YE', minLength: 9, maxLength: 9 },
  { name: 'Zambia', flag: '\u{1F1FF}\u{1F1F2}', code: '+260', isoCode: 'ZM', minLength: 9, maxLength: 9 },
  { name: 'Zimbabwe', flag: '\u{1F1FF}\u{1F1FC}', code: '+263', isoCode: 'ZW', minLength: 9, maxLength: 9 },
];
